Origin/yness/solver
GOPY-OCR/GOPY-OCR pull request #16
Opened 2022-10-21 15:36 UTC by YnessK

2022-10-22 15:23 UTC, Gregoire-perso commented on src/Solver/solver.c
> +    for (size_t i = lign; lign < lign + 3; i ++){
`lign < lign + 3` c'est toujours vrai ça non ? 👀

2022-10-22 15:23 UTC, Gregoire-perso commented on src/Solver/solver.c
> +        for (size_t j = column; column < column + 3; j ++){
`column < column + 3` ça aussi c'est toujours vrai non ? 👀

2022-10-22 15:34 UTC, Gregoire-perso commented
Ça me parait nickel pour le reste (reste plus qu'à tester). Juste est ce que tu pourrais : 
- supprimer les fichiers `.DS_Store` dans ton prochain commit (tu peux aussi l'ajouter au `.gitignore` dans le même commit pour pas l'ajouter automatiquement).
- ajouter un fichier `solver.h` avec au moins le prototype de la fonction principale et les include
- faire un fichier `main.c` qui prend un fichier en paramètre, et le résous en enregistrant la solution (tu peux utiliser les fonctions dispo dans le fichier `grid.h` pour lire et écrire les fichiers)
Comme ça c'est nickel et ça sera plus pratique pour la suite 😄

2022-10-25 11:59 UTC, Eldolfin commented
Tu dois ajouter Solver au Makefile des tests comme pour NeuralNetwork si tu veux qu'ils soient exécutés

2022-10-25 15:04 UTC, Gregoire-perso requested changes

2022-10-25 15:04 UTC, Gregoire-perso commented on tests/Makefile
> +    ./$@
```suggestion
.SECONDEXPANSION:
Solver: $(call ofiles,Solver)
	$(CC) $(CPPFLAGS) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(LDLIBS)
	./$@
```

2022-10-26 14:59 UTC, Gregoire-perso requested changes
Dans l'ensemble c'est pas trop mal malgré quelques erreurs par ci par là que j'ai commenté. 
Concernant la coding style c'est noice c'est joli à regarder
Concernant les tests, je sais pas trop pourquoi  il met autant de warnings, tu peux essayer de mettre l'initialisation de tes variables dans une fonction `setup` comme à fait Oscar, ça peut p'tet régler tous ces warnings

2022-10-26 14:59 UTC, Gregoire-perso commented on src/Solver/main.c
> +#include "grid.c"
```suggestion
#include "solver.h"
#include "grid.h"
```
Il faut jamais inclure les `.c` mais toujours les `.h` :eyes:

2022-10-26 14:59 UTC, Gregoire-perso commented on src/Solver/main.c
> +        err(1);
```suggestion
        errx(1, "You must give the file of the sudoku to solve");
```

2022-10-26 14:59 UTC, Gregoire-perso commented on src/Solver/main.c
> +        char file[strlen(file) + 7] = argv[1];
`strlen(file)` avant même que la variable soit déclarée ? 👀

2022-10-26 14:59 UTC, Gregoire-perso commented on src/Solver/solver.c
> +    while ((int)i < BOARDSIZE && list[i] != x)
Pourquoi cast le `i` en `int` ?

2022-10-26 14:59 UTC, Gregoire-perso commented on src/Solver/solver.c
> +    return ((int)i == BOARDSIZE) ? 0 : 1;
Same here, normalement tu as pas besoin

2022-10-26 14:59 UTC, Gregoire-perso commented on src/Solver/main.c
> +        Solve(grid);
Ici tu appelles ta fonction `Solve` qui prend un tableau à double dimension avec `grid` qui est un tableau à simple dimension en `raw major`

2022-10-26 14:59 UTC, Gregoire-perso commented on src/Solver/solver.h
> +int BOARDSIZE = 9;
Ici tu définies `BOARDSIZE` comme une variable globale, mais tu fais un `#define BOARDSIZE` dans ton `solver.c`, je te conseille de garder le `#define` mais de le mettre dans `solver.h`

2022-10-26 14:59 UTC, Gregoire-perso commented on tests/SolverTests/test_boards.c
> +        int contains = Contains(board[i][0], element2search);
Ici y'a les mauvais paramètres pour l'appel à `Contains`

2022-10-26 19:44 UTC, YnessK commented on src/Solver/main.c
> +#include "grid.c"
alors ça ça s'appelle se précipiter parce que je le sais pertinemment 😅

2022-10-26 19:48 UTC, YnessK commented on src/Solver/solver.c
> +    while ((int)i < BOARDSIZE && list[i] != x)
alors à la base j'étais en `size_t` et ca m'a mis un problème de comparaison avec 2 types différents donc j'ai cast en `int`

2022-10-26 19:49 UTC, YnessK commented on src/Solver/solver.h
> +int BOARDSIZE = 9;
je sais qu'il y a un problème avec ca j'ai essayé plusieurs solutions à chaque fois il y a un souci sur ca quand  je lance les tests

2022-10-26 19:50 UTC, YnessK commented on tests/SolverTests/test_boards.c
> +        int contains = Contains(board[i][0], element2search);
...

2022-10-26 19:53 UTC, YnessK commented on src/Solver/main.c
> +        Solve(grid);
du coup je dois créer le tableau à 2 dimensions à partir de grid puis appeler dans Solve kook

2022-10-26 22:39 UTC, Gregoire-perso commented on src/Solver/main.c
> +        char file[strlen(file) + 7] = argv[1];
Bah ui du coup

2022-10-26 22:46 UTC, Gregoire-perso approved these changes
C'est tout good pour moi du coup

2022-10-26 22:51 UTC, Eldolfin commented
Mais là les tests ne sont pas run :cry:

2022-10-27 22:37 UTC, merged